language: python
branches:
  only:
    - master
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
notifications:
  email:
  - apslite-ci@odin.com
script:
  - python setup.py flake8
  - python setup.py nosetests
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker build -t ingrammicro/fallball-connector .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ingrammicro/fallball-connector
